apiVersion: v1
kind: Service
metadata:
  name: polls-service
spec:
  selector:
    app: polls
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30008
  type: NodePort
